volumes:
    postgres_data: 

services:
  app-inmemory:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozontz-app-inmemory
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ["./my_ozontz_app", "-storage=inmemory"]
    profiles:
      - inmemory

  app-postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozontz-app-postgres
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=mydb
      - DB_PORT=5432
    command: ["./my_ozontz_app", "-storage=postgres"]
    profiles:
      - postgres
    volumes:
      - ./migrations:/ozontz_app/migrations
    depends_on:
    - db

  db:
    image: postgres:13
    container_name: ozontz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - postgres